/** Generated by YAKINDU Statechart Tools code generator. */
package hu.bme.mit.yakindu.analysis.example;

import hu.bme.mit.yakindu.analysis.IStatemachine;
import hu.bme.mit.yakindu.analysis.ITimerCallback;

public interface IExampleStatemachine extends ITimerCallback,IStatemachine {
	public interface SCInterface {
	
		public void raiseStart();
		
		public void raiseWhiteTest();
		
		public void raiseBlackTest();
		
		public long getWhiteTimeTest();
		
		public void setWhiteTimeTest(long value);
		
		public long getBlackTimeTest();
		
		public void setBlackTimeTest(long value);
		
	}
	
	public SCInterface getSCInterface();
	
}
